apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: spring-cloud-client-testing
spec:
    selector:
        matchLabels:
            app: spring-cloud-client-testing
    replicas: 1
    template:
        metadata:
            labels:
                app: spring-cloud-client-testing
        spec:
            containers:
                - name: spring-cloud-client-testing
                  image: configserverpocregistry.azurecr.io/spring-cloud-client-testing:v6
                  ports:
                    - containerPort: 9090
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: spring-cloud-client-testing
spec:
    type: LoadBalancer
    ports:
      - port: 9090
        targetPort: 9090
    selector:
      app: spring-cloud-client-testing