apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    selector:
        matchLabels:
            app: rabbitmq
    replicas: 1
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: configserverpocregistry.azurecr.io/rabbitmq:latest
                  ports:
                    - containerPort: 5672
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    ports:
      - port: 5672
        targetPort: 5672
    selector:
      app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-dashboard
spec:
    type: LoadBalancer
    ports:
      - port: 15672
        targetPort: 15672
    selector:
      app: rabbitmq