apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: spring-cloud-server
spec:
    selector:
        matchLabels:
            app: spring-cloud-server
    replicas: 1
    template:
        metadata:
            labels:
                app: spring-cloud-server
        spec:
            containers:
                - name: spring-cloud-server
                  image: configserverpocregistry.azurecr.io/spring-cloud-server:v7
                  ports:
                    - containerPort: 8888
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: spring-cloud-server
spec:
    type: LoadBalancer
    ports:
      - port: 8888
        targetPort: 8888
    selector:
      app: spring-cloud-server